### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by oliver-graetz** [MatMoul/firefox-gui-chrome-css#1]
Hi there!

I used your code and made some modifications for my needs. Perhaps you would like to use them as well:

- First of all for me the statusbar is mainly needed so the bottom border of the window is a safe resting place for the mouse pointer and to a lesser degree I also don't like the status text information popping up and vanishing all the time. I don't have the resting place problem when the window isn't maximized because then there is a window border. Therefore I only use the rules when the window is maximized. This also gets rid of some positioning problems of the status text when the window isn't maximized.
- Then I saw some strange dark pixel problems at the right edge of the status text. This was solved by adjusting the padding rule.

```
#main-window[sizemode="maximized"] #browser-bottombox { height: 20px; border-top: solid 1px #505050; }
#main-window[sizemode="maximized"] .browserContainer>statuspanel { left: 4px !important; bottom: 0px; transition-duration: 0s !important; transition-delay: 0s !important; }
#main-window[sizemode="maximized"] .browserContainer>statuspanel>.statuspanel-inner>.statuspanel-label { margin-left: 0px !important; border: none !important; padding: 0 2px 0 0 !important; }

window[inFullscreen="true"] #browser-bottombox { display:none !important; }
window[inFullscreen="true"] .browserContainer>statuspanel[type="overLink"] .statuspanel-label { display:none !important; }
```

**Comment by MatMoul** [comment]
Thank you for you return...
For me, I don't support the status text that override the page...
This is why I've tried to find a solution.
But I don't have saw the dark pixel...
I'm on linux with plasma5...
It's possible that on Windows or Mac the result are different.

**Comment by SentineI** [comment]
@MatMoul 
Thanks for your BRILLIANT userChrome.css magic :-) .  The loss of Status-4-Evar was the last thing putting me off upgrading to Firefox Quantum, and I find this a pretty good substitute.

I did however find that on Ubuntu & Windows, the status bar text was touching the bottom of the window, which looked wrong to me, so I increased the box size slightly:
```
#browser-bottombox {
	height: 23px;
	border-top: solid 1px #505050;
}
.browserContainer>statuspanel {
	left: 4px !important;
	bottom: 3px;
	transition-duration: 0s !important;
	transition-delay: 0s !important;
}
.browserContainer>statuspanel>.statuspanel-inner>.statuspanel-label {
	margin-left: 0px !important;
	border: none !important;
	padding: 0px !important;
}

window[inFullscreen="true"] #browser-bottombox {
	display:none !important;
}
window[inFullscreen="true"] .browserContainer>statuspanel[type="overLink"] .statuspanel-label {
	border: 1px solid #505050 !important;
	padding: 2px !important;
	/*display:none !important;*/
}
```
As you can see, I also added some line feeds to make it easier for me to follow.

I've also (for the moment at least) commented out the last part, to allow a status 'bubble' to appear when I mouse-over links in FullScreen mode.  And I've added a border & some padding to make it look better.

**Comment by SentineI** [comment]
I've updated my earlier post with a slightly improved CSS code...

**Comment by MatMoul** [comment]
@SentineI Thanks for your return, you'r right, on Windows, the top and bottom margin are not the same that on my Linux/Plasma5.
I've tested your changes and it work well on Windows but on my Plasma5 the bottom margin is to big.
I'll investigate and try to provide a compatible solution for all desktop.

**Comment by 9jkh** [comment]
Just discovered your css to add bottom box. Thanks, as it's very tiny, wondering now if there's anyway to increase the font size of the status text that appears there?

**Comment by 9jkh** [comment]
Found the following which works in FF57+ for color/font size in status bar.
/*Status Bar font/color*/
.statuspanel-label {font-size: 9.5pt !important;font-weight: normal !important;color: black !important;}

Only thing missing now from Status-4-Evar is the progress indicator, but not holding my breath for getting that back.

**Comment by SentineI** [comment]
@MatMoul
Firefox 61 broke your CSS code, but you then fixed it.  Many thanks!

My own customisations (see above) needed fixing as well, so here's the revised version in case anyone finds it useful:
```
#browser-bottombox {
	height: 23px;
	border-top: solid 1px #505050;
}
#statuspanel {
	width: 100% !important;
	left: 3px !important;/*changed from 0px*/
	bottom: 3px !important;/*changed from 0px*/
	padding: 0px !important;
	transition-duration: 0s !important;
	transition-delay: 0s !important;
	transition-property: none !important;
}
#statuspanel-label {
	top: 0px !important;
	margin-left: 0px !important;
	margin-top: 0px !important;
	border: none !important;
	padding: 0px !important;
}

window[inFullscreen="true"] #browser-bottombox {
	display:none !important;
}
window[inFullscreen="true"] #statuspanel {
	/*display:none !important;*/
}
window[inFullscreen="true"] #statuspanel-label {
	border: 1px solid #505050 !important;
	padding: 2px !important;
}
```

**Comment by MatMoul** [comment]
@SentineI Thank's for your return...
I need to wrap my code...
It's more easy to read...
