### ISSUE TITLE
Addons in it and Done after loading

### ISSUE THREAD

**Issue by Foxy44** [MatMoul/firefox-gui-chrome-css#2]
Hello,
Is there a way to put icons of AddOns in the bar?
And you can show a Done after loading?

Best regards

Jens

**Comment by SentineI** [comment]
I very much doubt AddOn icons can be put in the bar.  I've seen discussions about adding "Done" to status bar, but the CSS seemed very hacky/unreliable...

**Comment by MatMoul** [comment]
At this time, it's seem it's not possible...
Perhaps in the future...
Look the evolution of APIs or CSS
