### ISSUE TITLE
stopped working in Firefox 62

### ISSUE THREAD

**Issue by ramlaxman** [MatMoul/firefox-gui-chrome-css#3]
- Not working in FF 62.0.3

**Comment by valepu** [comment]
noticed the same thing. I still see the bottom bar but the statuspanel is now being showed above the bottombox

**Comment by valepu** [comment]
I made a pull request which should be fixing it https://github.com/MatMoul/firefox-gui-chrome-css/pull/4

**Comment by MatMoul** [comment]
Do you use the latest version from June?
I had made an update for FF61 and it work too for FF62
https://github.com/MatMoul/firefox-gui-chrome-css/issues/1#issuecomment-406030603

**Comment by ramlaxman** [comment]
It is showing status bar but not able to customize i.e. not able to drag extension to it.

**Comment by valepu** [comment]
I don't think that's ever been possible since FF 57

**Comment by MatMoul** [comment]
I confirm, this css file can only add a status bar for the url and not for extentions...
