### ISSUE TITLE
White bar permanently at bottom of fullscreen videos (I have fixed)

### ISSUE THREAD

**Issue by SentineI** [MatMoul/firefox-gui-chrome-css#5]
Firefox has changed how fullscreen is handled in CSS, because fullscreen videos now have a white bar permanently stuck at the bottom of the screen - which is unchanged from non-fullscreen mode.

I was able to fix this issue by changing:
`window[inFullscreen=`
To this:
`html[inFullscreen=`
(i.e. Replace "window" by "html".)

By the way, I find it looks better when using this in #statuspanel : 
`	left: 3px !important;/*I changed from 0px*/`
`	bottom: 2px !important;/*I changed from 0px*/`

One more thing, I dislike never seeing links while in full-screen, so I commented-out this at the end:
`/*html[inFullscreen="true"] #statuspanel {`
`	display:none !important;`
`}*/`

And added this at this after it:
`html[inFullscreen="true"] #statuspanel-label {`
`	border: 1px solid #505050 !important;`
`	padding-left: 2px !important;`
`	padding-bottom: 6px !important;`
`	background: white !important;`
`}`

**Comment by MatMoul** [comment]
Thanks for your feedback...
Your right for the full screen...
I'll test your other change soon...

**Comment by xR2** [comment]
Tested on Win10 and FF 76.0.1. 
Works nice.
