### ISSUE TITLE
Fix for FireFox 109

### ISSUE THREAD

**Issue by SentineI** [MatMoul/firefox-gui-chrome-css#7]
Since FireFox 109 this has stopped working, as the status bar itself is gone (i.e. no white background), with the text instead appearing directly over the website (and so can be very hard to read).

This is because FireFox 109 has removed the "browser-bottombox" HTML element:  
https://hg.mozilla.org/mozilla-central/rev/49cefc94b9bd58a75eb124083733caf3f90e28da

After some trial & error, I have been able to kludge the "a11y-announcement" element as a replacement for "browser-bottombox".  This may break some FireFox accessibility functionality, but I don't see any other solution.  Here is my fix:
```
:root:not([inFullscreen]) #a11y-announcement {
	/* Kludge to make "a11y-announcement" a replacement for the removed "browser-bottombox" element */
	display: block !important;
	/* Also give it the right colour - and Mozilla says "opaque for layers optimization" (although this may not apply) */
	background-color: var(--toolbar-bgcolor) !important;
}
#browser-bottombox, 
#a11y-announcement {
	height: 20px;
	border-top: solid 1px #505050;
}
#statuspanel {
	position: fixed !important;
	height: 20px !important;
	width: 100% !important;
	left: 0px !important;
	bottom: 0px !important;
	padding: 0px !important;
	transition-duration: 0s !important;
	transition-delay: 0s !important;
	transition-property: none !important;
}
#statuspanel-label {
	color: var(--toolbar-color) !important;
	background: transparent !important;
	border: none !important;
}

html[inFullscreen="true"] #browser-bottombox, 
html[inFullscreen="true"] #a11y-announcement {
	display:none !important;
}
html[inFullscreen="true"] #statuspanel {
	display:none !important;
}
```

By the way, I dislike that the status bar is completely invisible when a website is full-screen, so I fixed it to show as the old pop-up box instead, by replacing this:
```
html[inFullscreen="true"] #statuspanel {
	display:none !important;
}
```
With this:
```
html[inFullscreen="true"] #statuspanel-label {
	/* Make status text visible - as a pop-up box */
	border: 1px solid #505050 !important;
	padding-left: 2px !important;
	padding-bottom: 6px !important;
	background: var(--toolbar-bgcolor) !important;
}
```

**Comment by SentineI** [comment]
I've revised the CSS in the previous post to fix it to work with dark mode & themes in general.

**Comment by MatMoul** [comment]
Thanks for the solution, it seems to work for me...
You can submit a PR!

**Comment by SentineI** [comment]
Done!

**Comment by MatMoul** [comment]
Thanks for the good job...
